# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin('vagrant-dnsmasq')

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box'


  config.vm.hostname = 'myhost'

  config.dnsmasq.domain = '.dev'

  # optional
  config.dnsmasq.ip = '10.10.10.1'

end
